[update]
tasks = ["code", "normalize"]

[update.code]
codePaths = ["iOS App/Data"]
localizablePaths = ["iOS App/Localisations"]
defaultToKeys = false
additive = false
unstripped = false
plistArguments = true

[update.normalize]
paths = ["iOS App/Localisations", "Widget Extension/Localisation"]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
paths = ["iOS App/"]
duplicateKeys = true
emptyValues = true
